(function(){
var m={
"品質管理 基礎コース":[
"品質とは何か：お客様が決める「良い製品」",
"製造業の責任：製品とサービスにおける「品質」の定義と役割",
"品質管理の構造「設計」「製造」「安心」の3つの品質",
"全社員で取り組む品質：「狭義の品質」から「広義の品質」へ",
"品質管理の真の目的：「ばらつき」を抑えて品質を安定させる",
"「後工程はお客様」の考え方",
"SDCA：標準を守るサイクル",
"設計品質・製造品質・使用品質の関係",
"品質概念の基礎：お客様要求と当たり前品質"
],
"製造業 基礎知識コース":[
"製造業の責任：製品とサービスにおける「品質」の定義と役割",
"サプライチェーンとは",
"カンバン方式とは何か：必要なモノを必要な時に必要な量だけ",
"トレーサビリティとロット管理の重要性"
],
"現場力向上コース":[
"5Sの基本：整理・整頓・清掃・清潔・しつけ",
"三現主義：現場・現物・現実",
"ヒューマンエラー入門",
"報連相と5W1Hの基本",
"ポカヨケの考え方と事例研究",
"標準作業・タクトタイム・レイアウト改善"
],
"問題解決 基礎コース":[
"問題と課題の定義　「あるべき姿」と「ありたい姿」：「問題」と「課題」を正しく区別する",
"5W1Hを使った目的の明確化",
"なぜなぜとは？考え方と具体例"
],
"QC七つ道具コース":[
"QC七つ道具の概要と選び方",
"Excelで始めるQC七つ道具（基礎編）",
"パレート図・ヒストグラムの作り方",
"特性要因図（魚の骨）の描き方"
],
"統計・データ分析コース":[
"データで見る品質：なぜ数字が必要か",
"定量的データ分析の初歩：データの傾向を掴む：平均、範囲、分散、標準偏差の計算基礎",
"グラフの読み方と落とし穴",
"標本とは",
"母集団と標本のイメージをつかむ"
],
"検査・計測コース":[
"検査の目的と全数検査・抜き取り検査",
"検査標準と官能検査のポイント",
"受入検査の役割と運用ポイント（中小企業版）",
"抜き取り検査の設計とAQLの考え方"
],
"品質マネジメントシステムコース":[
"全社員で取り組む品質：「狭義の品質」から「広義の品質」へ",
"品質文書の維持管理：必要な時にすぐ見つかる「生きた文書」の管理",
"文書・記録・版管理の基礎",
"品質KPI設計と日常管理ボード",
"eQMSと現場データ活用入門"
],
"FMEA・源流管理コース":[
"FMEAの超入門",
"源流管理と未然防止：設計段階で不具合を潰す：FMEAと設計審査（DR）の活用",
"FMEAの進化とリスクマネジメント実践"
],
"変更管理・4M管理コース":[
"4Mと変化点：品質に影響する要因を知る",
"初期流動管理と変化点管理の実務"
],
"クレーム対応・是正処置コース":[
"是正処置の真因特定：「なぜなぜ問答」の適切な回数",
"なぜなぜとは？考え方と具体例"
],
"サプライヤ品質管理コース":[
"サプライヤ監査と是正要求の基本",
"下請け側から見た品質経営",
"受入検査の役割と運用ポイント（中小企業版）"
],
"品質コスト・KPI管理コース":[
"不良低減と生産性向上の関係",
"過剰品質と不足品質のリスク",
"品質KPI設計と日常管理ボード"
],
"リスクマネジメントコース":[
"異常のメカニズム：バスタブ曲線から学ぶ：初期故障と「ばらつき」の深い関係",
"FMEAの進化とリスクマネジメント実践"
],
"品質人材育成・組織マネジメントコース":[
"品質人材育成とOJT設計",
"改善能力の育成：集中改善会による意識改革と右脳活用"
],
"トヨタ生産方式コース":[
"トヨタ生産方式（TPS）とは",
"カンバン方式とは何か：必要なモノを必要な時に必要な量だけ",
"アンドン・カンバン・ボードによる見える化"
],
"標準化コース":[
"標準化の重要性 ～業務フローの可視化と再現性の確立",
"文書・記録・版管理の基礎",
"標準作業・タクトタイム・レイアウト改善"
],
"DX・データ活用コース":[
"eQMSと現場データ活用入門",
"eQMS運用ルールと電子記録の信頼性"
],
"健康食品GMPコース":[
"第1回：【効率化の鍵】最小限の労力で認証を取得するためのロードマップ",
"第2回：GMPの法的義務化と最新の規制動向",
"第3回：消費者庁・厚生労働省の指針解説",
"第5回：「品質確認」機能の役割と製造部門からの独立性の確保",
"第6回：GMP文書体系の整備と5大基準書の策定実務",
"第7回：ALCOA+の原則と適正な文書管理手順",
"第8回：製品標準書の作成実務",
"第9回：微生物等関連原材料への特別対応",
"第10回：原材料・資材の受入試験と管理実務",
"第11回：製造指図書・記録書の運用とダブルチェック",
"第12回：製造現場の衛生管理",
"第13回：構造設備の要件と交叉汚染防止",
"第14回：品質管理基準に基づく試験検査実務",
"第15回：バリデーションの実施計画と変更管理",
"第16回：逸脱管理と品質情報の原因究明・再発防止策",
"第18回：自己点検表を活用した模擬内部監査",
"第19回：GMP認定申請手続きの実際",
"第20回：GMPマークの適切な活用法と表示ルール",
"第21回：中小企業向け前編：GMP導入の第一歩",
"第22回：中小企業向け後編：現場の環境整備と認定取得への道",
"第23回：2025年版ガイドラインで新設された「品質確認」の業務"
],
"教養コース":[
"品質とは何か：お客様が決める「良い製品」",
"製造業の責任：製品とサービスにおける「品質」の定義と役割",
"品質管理の構造「設計」「製造」「安心」の3つの品質",
"全社員で取り組む品質：「狭義の品質」から「広義の品質」へ",
"トレーサビリティとロット管理の重要性",
"品質管理の真の目的：「ばらつき」を抑えて品質を安定させる",
"異常のメカニズム：バスタブ曲線から学ぶ",
"5Sの基本：整理・整頓・清掃・清潔・しつけ",
"「後工程はお客様」の考え方",
"ヒューマンエラー入門",
"4Mと変化点：品質に影響する要因を知る",
"問題と課題の定義：「問題」と「課題」を正しく区別する",
"SDCA：標準を守るサイクル",
"データで見る品質：なぜ数字が必要か",
"定量的データ分析の初歩",
"グラフの読み方と落とし穴",
"報連相と5W1Hの基本",
"三現主義：現場・現物・現実",
"サプライチェーンとは"
],
"初級コース":[
"5W1Hを使った目的の明確化",
"Excelで始めるQC七つ道具（基礎編）",
"FMEAの超入門",
"QC七つ道具の概要と選び方",
"設計品質・製造品質・使用品質の関係",
"カンバン方式とは何か",
"トヨタ生産方式（TPS）とは",
"なぜなぜとは？考え方と具体例",
"パレート図・ヒストグラムの作り方",
"過剰品質と不足品質のリスク",
"管理図による工程の異常早期発見",
"検査の目的と全数検査・抜き取り検査",
"検査標準と官能検査のポイント",
"源流管理と未然防止",
"受入検査の役割と運用ポイント（中小企業版）",
"特性要因図（魚の骨）の描き方",
"標準化の重要性",
"標本とは",
"品質概念の基礎：お客様要求と当たり前品質",
"品質文書の維持管理",
"不良低減と生産性向上の関係",
"文書・記録・版管理の基礎",
"母集団と標本のイメージをつかむ"
],
"中級コース":[
"eQMSと現場データ活用入門",
"サプライヤ監査と是正要求の基本",
"トレーサビリティ設計と情報項目",
"バリデーションとは何か",
"ポカヨケの考え方と事例研究",
"下請け側から見た品質経営",
"管理図の種類と使い分け（Xbar-R、p等）",
"初期流動管理と変化点管理の実務",
"是正処置の真因特定",
"抜き取り検査の設計とAQLの考え方",
"標準作業・タクトタイム・レイアウト改善",
"品質KPI設計と日常管理ボード"
],
"実践コース":[
"eQMS運用ルールと電子記録の信頼性",
"品質人材育成とOJT設計",
"FMEAの進化とリスクマネジメント実践",
"中小企業での管理図運用",
"海外拠点・サプライヤとの品質連携",
"改善能力の育成：集中改善会による意識改革と右脳活用",
"バリデーションの実施方法と注意点",
"アンドン・カンバン・ボードによる見える化"
]
};
/* CSS */
var style=document.createElement("style");
style.textContent=".course-content-section{border-top:1px solid rgba(255,255,255,.06);margin-top:12px;padding-top:12px}.course-content-toggle{display:flex;align-items:center;gap:6px;background:none;border:none;color:rgba(255,255,255,.6);font-size:12px;cursor:pointer;padding:4px 0;transition:color .2s;width:100%}.course-content-toggle:hover{color:rgba(255,255,255,.85)}.course-content-toggle .arrow{transition:transform .2s;font-size:10px}.course-content-toggle.open .arrow{transform:rotate(90deg)}.course-content-count{color:#6aacdd;font-weight:600}.course-content-list{display:none;margin-top:8px;padding:0;list-style:none}.course-content-list.show{display:block}.course-content-list li{font-size:12px;color:rgba(255,255,255,.7);padding:5px 8px;border-radius:4px;display:flex;align-items:flex-start;gap:6px;line-height:1.4}.course-content-list li:nth-child(odd){background:rgba(255,255,255,.02)}.course-content-list li::before{content:\"\u25B6\";font-size:7px;color:#6aacdd;flex-shrink:0;margin-top:4px}";
document.head.appendChild(style);
/* Inject */
document.querySelectorAll(".course-card").forEach(function(card){
var h3=card.querySelector("h3");
if(!h3)return;
var name=h3.textContent.trim();
var contents=m[name];
if(!contents||contents.length===0)return;
var footer=card.querySelector(".course-card-footer");
if(!footer)return;
var section=document.createElement("div");
section.className="course-content-section";
var btn=document.createElement("button");
btn.className="course-content-toggle";
btn.innerHTML='<span class="arrow">\u25B6</span> \uD83D\uDCFA \u30B3\u30F3\u30C6\u30F3\u30C4\u4E00\u89A7\uFF08<span class="course-content-count">'+contents.length+'</span>\u4EF6\uFF09';
var ul=document.createElement("ul");
ul.className="course-content-list";
contents.forEach(function(t){var li=document.createElement("li");li.textContent=t;ul.appendChild(li);});
btn.addEventListener("click",function(){
this.classList.toggle("open");
ul.classList.toggle("show");
});
section.appendChild(btn);
section.appendChild(ul);
card.insertBefore(section,footer);
});
})();
